routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Admin && Auth
Auth::routes();

Route::name('admin.')->middleware('roles:admin')->group(function (){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'Admin\Category\CategoryController')
        ->parameter('categories', 'hashid_category')
        ->except('show');

    Route::resource('tags', 'Admin\Tag\TagController')
        ->parameter('tags', 'hashid_tag')
        ->except('show');

    Route::resource('news', 'Admin\News\NewsController')
        ->parameter('news', 'hashid_news');
});


//SPA
Route::get('/{any}', 'Spa\SpaController@index')->where('any', '.*');

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Traits\HashidTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HashidTrait,
        SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'slug'
    ];

    protected $hidden = [
        'id'
    ];

    protected $appends = [
        'title',
        'hashId'
    ];

    /*
    |--------------------------------------------------------------------------
    | Mutator
    |--------------------------------------------------------------------------
    */

    /**
     * @return string
     */
    public function getTitleAttribute(): string
    {
        return ucwords(str_replace('-', ' ', $this->attributes['slug']));
    }

    /**
     * @param $value
     */
    public function setSlugAttribute($value): void
    {
        $this->attributes['slug'] = preg_replace('/\s+/', '-',strtolower($value));
    }


    /*
    |--------------------------------------------------------------------------
    | Relations
    |--------------------------------------------------------------------------
    */

    /**
     * @return BelongsTo
     */
    public function parent(): BelongsTo
    {
        return $this->belongsTo(self::class, 'parent_id', 'id');
    }

    /**
     * @return HasMany
     */
    public function children(): HasMany
    {
        return $this->hasMany(self::class, 'parent_id', 'id');

    }

    /**
     * @return HasMany
     */
    public function news(): HasMany
    {
        return $this->hasMany(News::class);
    }

    /*
    |--------------------------------------------------------------------------
    | Helpers
    |--------------------------------------------------------------------------
    */

    /**
     * @return HasMany
     */
    public function childrenRecursive():HasMany
    {
        return $this->children()->with('childrenRecursive');
    }

    /**
     * @return bool
     */
    public function isParent():bool
    {
        return boolval($this->children()->count());
    }

}

app/Http/Controllers/Admin/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Category;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Category\CategoryIndexRequest;
use App\Http\Requests\Admin\Category\CategoryStoreRequest;
use App\Http\Requests\Admin\Category\CategoryUpdateRequest;
use App\Models\Category;
use App\Services\Category\CategoryService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CategoryController extends Controller
{
    /**
     * @param CategoryIndexRequest $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(CategoryIndexRequest $request)
    {
        $categories = Category::with('parent')
            ->latest()
            ->paginate();
        return view('admin.category.index', compact('categories'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $parents = Category::query()->whereNull('parent_id')->get();
        return view('admin.category.create', compact('parents'));
    }

    /**
     * @param CategoryStoreRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CategoryStoreRequest $request)
    {
        $categoryService = CategoryService::new();
        $categoryService->afterCallback(function (Category $category) use ($request) {
            $category->parent()->associate($request->get('parent_id'));
        });
        $categoryService->create($request->only('slug'));

        return redirect()->route('admin.categories.index');
    }

    /**
     * @param $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($category)
    {
        $parents = Category::query()
            ->whereNull('parent_id')
            ->where('id', '!=',  $category->id)
            ->get();

        return view('admin.category.edit', compact('category','parents'));
    }

    /**
     * @param CategoryUpdateRequest $request
     * @param $category
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(CategoryUpdateRequest $request, $category)
    {
        $categoryService = CategoryService::make($category);
        $categoryService->afterCallback(function (Category $category) use ($request) {
            $category->parent()->associate($request->get('parent_id'));
        });
        $categoryService->update($request->only('slug'));

        return redirect()->route('admin.categories.index');
    }

    /**
     * @param Request $request
     * @param $category
     * @return \Illuminate\Http\RedirectResponse|Response
     */
    public function destroy(Request $request, $category)
    {
        if ($request->wantsJson()) {
            CategoryService::make($category)->delete();
            return response()->noContent(Response::HTTP_NO_CONTENT);
        } else {
            return redirect()->route('user.categories.index');
        }

    }
}

app/Http/Controllers/Api/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Api\Category;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\DefaultRequest;
use App\Http\Resources\CategoryResource;
use App\Http\Resources\NewsResource;
use App\Models\Category;
use App\Models\News;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * @return JsonResponse
     */
    public function index()
    {
        $categories = Category::with('childrenRecursive')
            ->whereNull('parent_id')
            ->get();
        return response()->json(CategoryResource::make($categories), JsonResponse::HTTP_OK);

    }

    /**
     * @param DefaultRequest $request
     * @param $category
     * @return JsonResponse
     */
    public function newsIndex(DefaultRequest $request, $category)
    {
        $news = News::withLocale($request->get('locale'))
            ->when($request->get('children'), function ($q) use ($category){
                $q->whereHas('category', function ($q) use ($category) {
                    $q->whereId($category->id)
                    ->orWhere('parent_id',$category->id);
                });
            })->when(!$request->get('children'), function ($q) use ($category) {
                $q->whereHas('category', function ($q) use ($category) {
                    $q->whereId($category->id);
                });
            })->whereNotNull('published_at')
            ->with('category')
            ->latest()
            ->paginate($request->get('count'));

        return response()->json(NewsResource::make($news), JsonResponse::HTTP_OK);
    }

}

resources/views/admin/category/create.blade.php
@extends('layouts.layout')

@section('content')

    <div class="card">
        <div class="card-header">{{ __('Create category') }}</div>

        <div class="card-body">
            <form action="{{ route('admin.categories.store') }}" class="form" method="post" id="category">
            @csrf
            @method('post')

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label class="form-label">{{ __('Title') }}<span class="text-danger">*</span><span class="small"> {{ __('Contains alphabet and space') }}</span></label>
                        <input id="slug" type="text" class="form-control @error('slug') is-invalid @enderror"
                               name="slug" value="{{ old('slug') }}" placeholder="Business"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'slug'])
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 ">
                        <label class="form-label">{{ __('Parent') }}</label>
                        <select class="form-control @error('parent_id') is-invalid @enderror" data-style="btn-default" data-live-search="true" name="parent_id">
                            <option></option>
                            @foreach($parents as $parent)
                                <option data-tokens="{{ $parent->title }}" value="{{ $parent->hashid }}"  {{ old('parent_id') == $parent->hashid ? 'selected' : '' }}>{{ $parent->title }}</option>
                            @endforeach
                        </select>
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'parent_id'])
                        </div>
                    </div>
                </div>

                <div class="text-right">
                    <button type="submit" class="btn btn-success">{{ __('Submit') }}</button>
                </div>

            </form>
        </div>
    </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.layout')

@section('content')

    <div class="card">
        <div class="card-header">{{ __('Edit category') }}</div>

        <div class="card-body">
            <form action="{{ route('admin.categories.update', $category->hashid) }}" class="form" method="post" id="category">
                @csrf
                @method('put')

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label class="form-label">{{ __('Title') }}<span class="text-danger">*</span><span class="small"> {{ __('Contains alphabet and space') }}</span></label>
                        <input id="slug" type="text" class="form-control @error('slug') is-invalid @enderror"
                               name="slug" value="{{ old('slug', $category->title) }}" placeholder="Business"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'slug'])
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 ">
                        <label class="form-label">{{ __('Parent') }}

                            @if($isParent = $category->isParent())
                                <span class="text-danger">*</span><span class="small"> {{ __('Currently parent') }}</span>
                            @endif
                        </label>
                        <select @if($isParent) disabled @endif class="form-control @error('parent_id') is-invalid @enderror" data-style="btn-default" data-live-search="true" name="parent_id">
                            <option></option>
                            @foreach($parents as $parent)
                                <option data-tokens="{{ $parent->title }}" value="{{ $parent->hashid }}"  {{ old('parent_id', $parent->hashid) == optional($category->parent)->hashid ? 'selected' : '' }}>{{ $parent->title }}</option>
                            @endforeach
                        </select>
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'parent_id'])
                        </div>
                    </div>
                </div>

                <div class="text-right">
                    <button type="submit" class="btn btn-success">{{ __('Submit') }}</button>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.layout')

@section('content')

    <div class="card">
        <div class="card-header">{{ __('Categories') }}</div>

        <div class="card-body">

            <div class="text-right mb-2">
                <a href="{{route('admin.categories.create')}}" type="submit" class="btn btn-success">{{ __('Create a category') }}</a>
            </div>
            @if(!$categories->isEmpty())
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">{{__('Title') }}</th>
                    <th scope="col">{{ __('Parent') }}</th>
                    <th scope="col">{{ __('Created at') }}</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $category)
                    <tr>
                        <th scope="row">{{ $loop->iteration }}</th>
                        <td>{{ $category->title }}</td>
                        <td>{{ optional($category->parent)->title }}</td>
                        <td>{{ $category->created_at }}</td>
                        <td>
                            <a href="{{ route('admin.categories.edit', $category->hashid) }}">{{ __('Edit') }}</a> |
                            <delete-button
                                endpoint="{{ route('admin.categories.destroy', $category->hashid) }}"
                                label="{{ __('Delete') }}"
                                text="{{ __("By deleting this category, all childrens are gonna be deleted too. Still wanna delete?") }}"
                            ></delete-button>

                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div class="p-2 mt-2">
                {{ $categories->render() }}
            </div>
            @else
                No Category Found
            @endif
        </div>
    </div>

@endsection