routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Admin && Auth
Auth::routes();

Route::name('admin.')->middleware('roles:admin')->group(function (){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'Admin\Category\CategoryController')
        ->parameter('categories', 'hashid_category')
        ->except('show');

    Route::resource('tags', 'Admin\Tag\TagController')
        ->parameter('tags', 'hashid_tag')
        ->except('show');

    Route::resource('news', 'Admin\News\NewsController')
        ->parameter('news', 'hashid_news');
});


//SPA
Route::get('/{any}', 'Spa\SpaController@index')->where('any', '.*');

app/Models/Tag.php
<?php

namespace App\Models;

use App\Models\Traits\HashidTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Tag extends Model
{
    use HashidTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'slug'
    ];

    protected $hidden = [
        'pivot'
    ];

    public  static function boot() {
        parent::boot();
        static::deleting(function (Tag $tag) {
            $tag->news()->detach();
        });
    }

    /*
    |--------------------------------------------------------------------------
    | Mutator
    |--------------------------------------------------------------------------
    */

    /**
     * @param $value
     */
    public function setSlugAttribute($value): void
    {
        $this->attributes['slug'] = preg_replace('/\s+/', ' ',strtolower($value));
    }

    /*
    |--------------------------------------------------------------------------
    | Relations
    |--------------------------------------------------------------------------
    */

    /**
     * @return BelongsToMany
     */
    public function news(): BelongsToMany
    {
        return $this->belongsToMany(News::class);
    }

    /*
    |--------------------------------------------------------------------------
    | Helpers
    |--------------------------------------------------------------------------
    */
}

app/Http/Controllers/Admin/Tag/TagController.php
<?php

namespace App\Http\Controllers\Admin\Tag;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Tag\TagStoreRequest;
use App\Http\Requests\Admin\Tag\TagUpdateRequest;
use App\Models\Tag;
use App\Services\Tag\TagService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class TagController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $tags = Tag::query()->paginate();
        return view('admin.tag.index', compact('tags'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * @param TagStoreRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(TagStoreRequest $request)
    {
        $inputs = $request->only('slug');
        $tagService = TagService::new();
        $tagService->create($inputs)->save();
        return redirect()->route('admin.tags.index');
    }

    /**
     * @param $tag
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($tag)
    {
        return view('admin.tag.edit', compact('tag'));
    }

    /**
     * @param TagUpdateRequest $request
     * @param $tag
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(TagUpdateRequest $request, $tag)
    {
        $inputs = $request->only('slug');
        TagService::make($tag)->update($inputs);
        return redirect()->route('admin.tags.index');
    }

    /**
     * @param Request $request
     * @param $tag
     * @return \Illuminate\Http\RedirectResponse|Response
     */
    public function destroy(Request $request, $tag)
    {
        if ($request->wantsJson()) {
            TagService::make($tag)->delete();
            return response()->noContent(Response::HTTP_NO_CONTENT);
        } else {
            return redirect()->route('user.tags.index');
        }
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.layout')

@section('content')

    <div class="card">
        <div class="card-header">{{ __('Create tag') }}</div>

        <div class="card-body">
            <form action="{{ route('admin.tags.store') }}" class="form" method="post" id="tag">
                @csrf
                @method('post')

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label class="form-label">{{ __('Title') }}<span class="text-danger">*</span><span class="small"> {{ __('Contains alphabet and space') }}</span></label>
                        <input id="slug" type="text" class="form-control @error('slug') is-invalid @enderror"
                               name="slug" value="{{ old('slug') }}" placeholder="Business"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'slug'])
                        </div>
                    </div>
                </div>

                <div class="text-right">
                    <button type="submit" class="btn btn-success">{{ __('Submit') }}</button>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/tag/edit.blade.php
@extends('layouts.layout')

@section('content')

    <div class="card">
        <div class="card-header">{{ __('Edit category') }}</div>

        <div class="card-body">
            <form action="{{ route('admin.tags.update', $tag->hashid) }}" class="form" method="post" id="tag">
                @csrf
                @method('put')

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label class="form-label">{{ __('Title') }}<span class="text-danger">*</span><span class="small"> {{ __('Contains alphabet and space') }}</span></label>
                        <input id="slug" type="text" class="form-control @error('slug') is-invalid @enderror"
                               name="slug" value="{{ old('slug', $tag->slug) }}" placeholder="Business"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'slug'])
                        </div>
                    </div>
                </div>

                <div class="text-right">
                    <button type="submit" class="btn btn-success">{{ __('Submit') }}</button>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/tag/index.blade.php
@extends('layouts.layout')

@section('content')

    <div class="card">
        <div class="card-header">{{ __('Tags') }}</div>

        <div class="card-body">

            <div class="text-right mb-2">
                <a href="{{route('admin.tags.create')}}" type="submit" class="btn btn-success">{{ __('Create a tag') }}</a>
            </div>
            @if(!$tags->isEmpty())

            <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">{{__('Title') }}</th>
                        <th scope="col">{{ __('Created at') }}</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tags as $tag)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ $tag->slug }}</td>
                            <td>{{ $tag->created_at }}</td>
                            <td>
                                <a href="{{ route('admin.tags.edit', $tag->hashid) }}">{{ __('Edit') }}</a> |
                                <delete-button
                                    endpoint="{{ route('admin.tags.destroy', $tag->hashid) }}"
                                    label="{{ __('Delete') }}"
                                    text="{{ __("By deleting this tag, It's gonna be removed from related news. Still wanna delete?") }}"
                                ></delete-button>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                <div class="p-2 mt-2">
                    {{ $tags->render() }}
                </div>
            @else
                No Tag Found
            @endif
        </div>
    </div>

@endsection