routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Admin && Auth
Auth::routes();

Route::name('admin.')->middleware('roles:admin')->group(function (){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'Admin\Category\CategoryController')
        ->parameter('categories', 'hashid_category')
        ->except('show');

    Route::resource('tags', 'Admin\Tag\TagController')
        ->parameter('tags', 'hashid_tag')
        ->except('show');

    Route::resource('news', 'Admin\News\NewsController')
        ->parameter('news', 'hashid_news');
});


//SPA
Route::get('/{any}', 'Spa\SpaController@index')->where('any', '.*');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">


    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('layout')
        </main>
    </div>
</body>
</html>

resources/views/layouts/layout.blade.php
@extends('layouts.app')

@section('layout')
<div class="container">

    @auth
        <div class="row">
            <div class="col-md-4 mt-0 pt-0">
                @include('layouts.sidebar')
            </div>
            <div class="col-md-8">
                @yield('content')
            </div>
        </div>
    @endauth

    @guest
            <div class="container-fluid flex-grow-1 container-p-y col-md-6">
                @yield('content')
            </div>
    @endguest


</div>
@endsection

resources/views/layouts/sidebar.blade.php
    <ul class="list-group">
        <li class="list-group-item">{{__('Articles')}}</li>
        <a class="list-group-item  pl-5" href="{{ route('admin.news.index') }}">List</a>
        <a class="list-group-item  pl-5" href="{{ route('admin.news.create') }}">Add an article</a>
        <li class="list-group-item">{{__('Categories')}}</li>
        <a class="list-group-item  pl-5" href="{{ route('admin.categories.index') }}">List</a>
        <a class="list-group-item  pl-5" href="{{ route('admin.categories.create') }}">Add a Category</a>
        <li class="list-group-item">{{__('Tags')}}</li>
        <a class="list-group-item  pl-5" href="{{ route('admin.tags.index') }}">List</a>
        <a class="list-group-item  pl-5" href="{{ route('admin.tags.create') }}">Add a tag</a>

    </ul>