routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Admin && Auth
Auth::routes();

Route::name('admin.')->middleware('roles:admin')->group(function (){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'Admin\Category\CategoryController')
        ->parameter('categories', 'hashid_category')
        ->except('show');

    Route::resource('tags', 'Admin\Tag\TagController')
        ->parameter('tags', 'hashid_tag')
        ->except('show');

    Route::resource('news', 'Admin\News\NewsController')
        ->parameter('news', 'hashid_news');
});


//SPA
Route::get('/{any}', 'Spa\SpaController@index')->where('any', '.*');

app/Models/News.php
<?php

namespace App\Models;

use App\Models\Traits\HashidTrait;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class News extends Model
{
    use HashidTrait,
        SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'external_url',
        'summary',
        'body',
        'category_id',
        'status_id',
        'published_at',
        'locale'
    ];

    protected $casts = [
        'published_at' => 'datetime'
    ];

    protected $hidden = [
        'id',
        'category_id',
        'status_id',
        'locale'
    ];

    protected $appends = [
        'hashId',
    ];

    /*
    |--------------------------------------------------------------------------
    | Mutator
    |--------------------------------------------------------------------------
    */

    public function getTagsAttribute()
    {
        return implode(',', $this->tags()->pluck('slug')->toArray());
    }


    /*
    |--------------------------------------------------------------------------
    | Relations
    |--------------------------------------------------------------------------
    */

    /**
     * @return BelongsToMany
     */
    public function tags(): BelongsToMany
    {
        return $this->belongsToMany(Tag::class)->select(array('id', 'slug'));
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class)->select(array('id', 'slug'));
    }

    /**
     * @return BelongsTo
     */
    public function status(): BelongsTo
    {
        return $this->belongsTo(Status::class)->select(array('id', 'slug'));
    }
    /*
    |--------------------------------------------------------------------------
    | Helpers
    |--------------------------------------------------------------------------
    */

    /**
     * @param Builder $builder
     * @param string|null $local
     * @return Builder
     */
    public function scopeWithLocale(Builder $builder, string $local = null): Builder
    {
        return $local ? $builder->whereLocale($local) : $builder;
    }
}

app/Http/Controllers/Admin/News/NewsController.php
<?php

namespace App\Http\Controllers\Admin\News;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\News\NewsStoreRequest;
use App\Http\Requests\Admin\News\NewsUpdateRequest;
use App\Models\Category;
use App\Models\News;
use App\Models\Status;
use App\Services\News\NewsService;
use App\Services\Tag\TagService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Http\Response;

class NewsController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $news = News::with(['status'])->latest()->paginate();
        return view('admin.news.index', compact('news'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $categories = Category::with('childrenRecursive')
            ->whereNull('parent_id')
            ->get();

        $statuses = Cache::rememberForever('statuses', function () {
            return Status::whereIn('slug', ['published', 'draft'])->get();
        });
        return view('admin.news.create', compact('categories', 'statuses'));
    }

    /**
     * @param NewsStoreRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(NewsStoreRequest $request)
    {
        $inputs = $request->only('title', 'external_url', 'summary', 'body', 'status_id', 'category_id', 'tags');
        $newsService = NewsService::new();
        $newsService->afterCallback(function (News $news) use ($inputs) {
            $news->status()->associate($inputs['status_id']);
            $news->category()->associate($inputs['category_id']);

            collect($inputs['tags'])->map(function ($tag) use (&$tags){
                $tags[]['slug'] = $tag;
            });
            if($inputs['tags']) {
                $tagService = TagService::new();
                $tagService = $tagService->firstOrCreateMany($tags);
                $news->tags()->sync($tagService);
            }

        });
        $newsService->create($inputs);

        return redirect()->route('admin.news.index');
    }


    /**
     * @param $news
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($news)
    {
        $categories = Category::with('childrenRecursive')
            ->whereNull('parent_id')
            ->get();

        $statuses = Cache::rememberForever('statuses', function () {
            return Status::whereIn('slug', ['published', 'draft'])->get();
        });

        return view('admin.news.edit', compact('news', 'statuses', 'categories'));
    }

    /**
     * @param NewsUpdateRequest $request
     * @param $news
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(NewsUpdateRequest $request, $news)
    {
        $inputs = $request->only('title', 'external_url', 'summary', 'body', 'status_id', 'category_id', 'tags');
        $newsService = NewsService::make($news);
        $newsService->afterCallback(function (News $news) use ($inputs) {

            $news->status()->associate($inputs['status_id']);
            $news->category()->associate($inputs['category_id']);


            collect($inputs['tags'])->map(function ($tag) use (&$tags){
                $tags[]['slug'] = $tag;
            });

            if($inputs['tags']) {
                $tagService = TagService::new();
                $tagService = $tagService->firstOrCreateMany($tags);
                $news->tags()->sync($tagService);
            }else {
                $news->tags()->detach();
            }

        });
        $newsService->update($inputs);

        return redirect()->route('admin.news.index');
    }

    /**
     * @param Request $request
     * @param $news
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Request $request, $news)
    {
        if ($request->wantsJson()) {
            NewsService::make($news)->delete();
            return response()->noContent(Response::HTTP_NO_CONTENT);
        } else {
            return redirect()->route('user.tags.index');
        }
    }
}

app/Http/Controllers/Api/News/NewsController.php
<?php

namespace App\Http\Controllers\Api\News;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\DefaultRequest;
use App\Http\Resources\NewsResource;
use App\Models\News;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    /**
     * @param DefaultRequest $request
     * @return JsonResponse
     */
    public function index(DefaultRequest $request)
    {
        $news = News::withLocale($request->get('locale'))
            ->whereHas('status', function ($q){
                $q->whereSlug('published');
            })->with(['category'])
            ->paginate($request->get('count'));

        return response()->json(NewsResource::make($news), JsonResponse::HTTP_OK);
    }

    /**
     * @param $news
     * @return JsonResponse
     */
    public function show($news)
    {
        return response()->json(NewsResource::make($news), JsonResponse::HTTP_OK);
    }

    /**
     * @param $locale
     * @param $slug
     * @return JsonResponse
     */
    public function showByUrl($locale, $slug)
    {
        $externalUrl = "{$locale}/article/{$slug}";
        $news = News::whereExternalUrl($externalUrl)->with(['category', 'tags'])->firstOrFail();

        return response()->json(NewsResource::make($news), JsonResponse::HTTP_OK);

    }
}

resources/views/admin/news/create.blade.php
@extends('layouts.layout')

@section('content')

    <div class="card">
        <div class="card-header">{{ __('Add news') }}</div>

        <div class="card-body">
            <form action="{{ route('admin.news.store') }}" class="form" method="post" id="news">
                @csrf
                @method('post')

                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="form-label">{{ __('Title') }}</label>
                        <input id="title" type="text" class="form-control @error('title') is-invalid @enderror"
                               name="title" value="{{ old('title') }}" placeholder="Business"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'title'])
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="form-label">{{ __('External Url') }}<span class="small"> {{ __('Desirable Structure: {locale}/article/{slug}') }}</span></label>
                        <input id="external_url" type="text" class="form-control @error('external_url') is-invalid @enderror"
                               name="external_url" value="{{ old('external_url') }}" placeholder="de/article/cAdweCX"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'external_url'])
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="form-label">{{ __('Summary') }}</label>
                        <textarea id="summary" type="text" class="form-control @error('slug') is-invalid @enderror"
                                  name="summary">{{ old('summary') }}</textarea>
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'summary'])
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="form-label">{{ __('Body') }}</label>
                        <textarea id="body" type="text" class="form-control @error('body') is-invalid @enderror"
                                  name="body">{{ old('body') }}</textarea>
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'body'])
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 ">
                        <label class="form-label">{{ __('Category') }}</label>
                        <select class="form-control @error('category_id') is-invalid @enderror" data-style="btn-default" data-live-search="true" name="category_id">
                            <option></option>
                            @foreach($categories as $category)
                                <optgroup label="main">
                                    <option data-tokens="{{ $category->title }}" value="{{ $category->hashid }}"  {{ old('category_id') == $category->hashid ? 'selected' : '' }}>{{ $category->title }}</option>
                                    @if($category->childrenRecursive()->count())
                                        <optgroup label="subs">
                                        @foreach($category->childrenRecursive as $child)
                                            <option data-tokens="{{ $child->title }}" value="{{ $child->hashid }}"  {{ old('category_id') == $child->hashid ? 'selected' : '' }}>{{ $child->title }}</option>
                                        @endforeach
                                        </optgroup>
                                    @endif
                                </optgroup>
                            @endforeach
                        </select>
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'category_id'])
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label">{{ __('Tags') }}<span class="small"> {{ __('Seperate tags with ,') }}</span></label>
                        <input id="tags" type="text" class="form-control @error('tags') is-invalid @enderror"
                               name="tags" value="{{ old('tags') }}" placeholder="Business, Job"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'tags'])
                        </div>
                    </div>
                </div>


                <div class="text-right">
                    <button type="submit" name="status_id" value="{{ $id = $statuses->firstWhere('slug','published')->hashId }}" id="publish" class="btn btn-success">{{ __('Publish') }}</button>
                    <button type="submit" name="status_id" value="{{ $id = $statuses->firstWhere('slug','draft')->hashId }}" id="draft" class="btn btn-primary">{{ __('Save draft') }}</button>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/news/edit.blade.php
@extends('layouts.layout')

@section('content')

    <div class="card">
        <div class="card-header">{{ __('Edit news') }}</div>

        <div class="card-body">
            <form action="{{ route('admin.news.update', $news->hashid) }}" class="form" method="post" id="news">
                @csrf
                @method('put')

                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="form-label">{{ __('Title') }}</label>
                        <input id="title" type="text" class="form-control @error('title') is-invalid @enderror"
                               name="title" value="{{ old('title', $news->title) }}" placeholder="Business"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'title'])
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="form-label">{{ __('External Url') }}<span class="small"> {{ __('Desirable Structure: {locale}/article/{slug}') }}</span></label>
                        <input id="external_url" type="text" class="form-control @error('external_url') is-invalid @enderror"
                               name="external_url" value="{{ old('external_url', $news->external_url) }}" placeholder="de/article/cAdweCX"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'external_url'])
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="form-label">{{ __('Summary') }}</label>
                        <textarea id="summary" type="text" class="form-control @error('summary') is-invalid @enderror"
                                  name="summary">{{ old('summary',$news->summary) }}</textarea>
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'summary'])
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <label class="form-label">{{ __('Body') }}</label>
                        <textarea id="body" type="text" class="form-control @error('body') is-invalid @enderror"
                                  name="body">{{ old('body', $news->body) }}</textarea>
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'body'])
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 ">
                        <label class="form-label">{{ __('Category') }}</label>
                        <select class="form-control @error('category_id') is-invalid @enderror" data-style="btn-default" data-live-search="true" name="category_id">
                            <option></option>
                            @foreach($categories as $category)
                                <optgroup label="main">
                                    <option data-tokens="{{ $category->title }}" value="{{ $category->hashid }}"  {{ old('category_id', optional($news->category)->hashid) == $category->hashid ? 'selected' : '' }}>{{ $category->title }}</option>
                                    @if($category->childrenRecursive()->count())
                                        <optgroup label="subs">
                                            @foreach($category->childrenRecursive as $child)
                                                <option data-tokens="{{ $child->title }}" value="{{ $child->hashid }}"  {{ old('category_id', optional($news->category)->hashid) == $child->hashid ? 'selected' : '' }}>{{ $child->title }}</option>
                                            @endforeach
                                        </optgroup>
                                    @endif
                                </optgroup>
                            @endforeach
                        </select>
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'category_id'])
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label">{{ __('Tags') }}<span class="small"> {{ __('Seperate tags with ,') }}</span></label>
                        <input id="tags" type="text" class="form-control @error('tags') is-invalid @enderror"
                               name="tags" value="{{ old('tags', $news->tags) }}" placeholder="Business, Job"  >
                        <div class="input">
                            @include('layouts.include.field', ['field' => 'tags'])
                        </div>
                    </div>
                </div>


                <div class="text-right">
                    <button type="submit" name="status_id" value="{{ $id = $statuses->firstWhere('slug','published')->hashId }}" id="publish" class="btn btn-success">{{ __('Publish') }}</button>
                    <button type="submit" name="status_id" value="{{ $id = $statuses->firstWhere('slug','draft')->hashId }}" id="draft" class="btn btn-primary">{{ __('Save draft') }}</button>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/news/index.blade.php
@extends('layouts.layout')

@section('content')

    <div class="card">
        <div class="card-header">{{ __('News') }}</div>

        <div class="card-body">

            <div class="text-right mb-2">
                <a href="{{route('admin.news.create')}}" type="submit" class="btn btn-success">{{ __('Add an article') }}</a>
            </div>
            @if(!$news->isEmpty())
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">{{__('Title') }}</th>
                        <th scope="col"></th>
                        <th scope="col">{{ __('Created at') }}</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($news as $item)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ $item->title }}</td>
                            <td>
                                @if($item->status->slug=='draft')
                                    @php($class='secondary')
                                @elseif($item->status->slug=='published')
                                    @php($class='success')
                                @elseif($item->status->slug=='scheduled')
                                    @php($class='primary')
                                @else
                                    @php($class='light')
                                @endif
                                <span class="badge badge-{{$class}}">{{ $item->status->slug }}</span>
                            </td>
                            <td>{{ $item->created_at }}</td>
                            <td>
                                <a href="{{ route('admin.news.edit', $item->hashid) }}">{{ __('Edit') }}</a> |
                                <delete-button
                                    endpoint="{{ route('admin.news.destroy', $item->hashid) }}"
                                    label="{{ __('Delete') }}"
                                    text="{{ __("Are you sure?") }}"
                                ></delete-button>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                <div class="p-2 mt-2">
                    {{ $news->render() }}
                </div>
            @else
                No Tag Found
            @endif
        </div>
    </div>

@endsection